<a href="https://colab.research.google.com/github/rgsrinidhi/MLprojects/blob/main/PCA_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#PCA Implementation using numpy scikit learn

In [1]:
import numpy as np

In [14]:
from os import EX_CONFIG
import numpy as np
X = np.array([[1,2,1],[3,4,3],[5,6,5],[7,8,7],[9,12,9]],dtype=float)
print(X)

#Step 1
#find x and y mean

mean = X.mean(axis = 0)
print(mean)
X_Centered = X-mean
print(X_Centered)
#Step 2
#Covariance matrix

cov_mat = np.cov(X_Centered, rowvar = False)
print(cov_mat)

#Step 3
#Eigen Values

eigvals, eigvecs = np.linalg.eigh(cov_mat)
print(eigvals)
# print(eigvecs)

#Step 4
# descendint order
order = np.argsort(eigvals)[::-1]
print("order")
print(order)
eigvals = eigvals[order]
eigvecs = eigvecs[:,order]

print(eigvals)
print(eigvecs)

#Step 5
#explained variance ratio

explained_variance_ratio = eigvals /eigvals.sum()
print(explained_variance_ratio)

#Step 6
X_pca = X_Centered @ eigvecs
print(X_pca)



[[ 1.  2.  1.]
 [ 3.  4.  3.]
 [ 5.  6.  5.]
 [ 7.  8.  7.]
 [ 9. 12.  9.]]
[5.  6.4 5. ]
[[-4.  -4.4 -4. ]
 [-2.  -2.4 -2. ]
 [ 0.  -0.4  0. ]
 [ 2.   1.6  2. ]
 [ 4.   5.6  4. ]]
[[10.  12.  10. ]
 [12.  14.8 12. ]
 [10.  12.  10. ]]
[-6.42699800e-15  2.31424054e-01  3.45685759e+01]
order
[2 1 0]
[ 3.45685759e+01  2.31424054e-01 -6.42699800e-15]
[[-5.36525737e-01  4.60586727e-01 -7.07106781e-01]
 [-6.51367996e-01 -7.58761974e-01  2.44249065e-14]
 [-5.36525737e-01  4.60586727e-01  7.07106781e-01]]
[ 9.93349883e-01  6.65011651e-03 -1.84683851e-16]
[[ 7.15822508e+00 -3.46141129e-01  1.06581410e-14]
 [ 3.70938614e+00 -2.13181696e-02  4.44089210e-16]
 [ 2.60547198e-01  3.03504790e-01 -9.76996262e-15]
 [-3.18829174e+00  6.28327749e-01 -1.99840144e-14]
 [-7.93986668e+00 -5.64373240e-01  1.86517468e-14]]
