<a href="https://colab.research.google.com/github/rgsrinidhi/MLprojects/blob/main/simple_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

class Perceptron(object):
 def __init__(self,eta=0.01,n_iter=10):
  self.eta = 0.01
  self.n_iter = 10

 def weighted_sum(self,X):
  return np.dot(X,self.w_[1:])+self.w_[0]

 def predict(self,X):
  return np.where(self.weighted_sum(X)>=0.0,1,-1)

 def fit(self,X,y):
  self.w_ = np.zeros(1+X.shape[1])
  self.errors =[]

  print("Weights ", self.w_)

  for _ in range (0,self.n_iter):
    error = 0
    for xi,target in zip(X,y):
      y_predict = self.predict(xi)

      update = self.eta * (target-y_predict)

      self.w_[1:]=self.w_[1:]+update*xi

      self.w_[0]=self.w_[0]+update

      error+=int(update!= 0.0)

      print("Weights ",_,self.w_)

    self.errors.append(error)


    self.errors.append(error)
  return self

In [ ]:
import pandas as pd
from sklearn.utils import shuffle
import numpy as np

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
# Shuffling the data
df = shuffle(df)

df.head()

0    1    2    3                4
37   4.9  3.1  1.5  0.1      Iris-setosa
66   5.6  3.0  4.5  1.5  Iris-versicolor
91   6.1  3.0  4.6  1.4  Iris-versicolor
119  6.0  2.2  5.0  1.5   Iris-virginica
7    5.0  3.4  1.5  0.2      Iris-setosa

In [ ]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

print(X[0:5])
print(y[0:5])

[[4.9 3.1 1.5 0.1]
 [5.6 3.  4.5 1.5]
 [6.1 3.  4.6 1.4]
 [6.  2.2 5.  1.5]
 [5.  3.4 1.5 0.2]]
['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa']


In [ ]:
#test and train split
from sklearn.model_selection import train_test_split

train_data, test_data ,train_labels, test_labels = train_test_split(X,y,test_size=0.25)
train_labels = np.where(train_labels == 'Iris-setosa',1,-1)
test_labels = np.where(test_labels == 'Iris-setosa',1,-1)

print('Train data: ', train_data[0:2])
print('Train labels: ', train_labels[0:5])

print('Test data: ',test_data[0,2])
print('Test labels: ',test_labels[0:5])


Train data:  [[5.3 3.7 1.5 0.2]
 [5.1 3.8 1.5 0.3]]
Train labels:  [ 1  1  1 -1 -1]
Test data:  1.3
Test labels:  [ 1  1 -1 -1  1]


In [ ]:
perceptron = Perceptron(eta=0.1, n_iter=10)
perceptron.fit(train_data, train_labels)

Weights  [0. 0. 0. 0. 0.]
Weights  0 [0. 0. 0. 0. 0.]
Weights  0 [0. 0. 0. 0. 0.]
Weights  0 [0. 0. 0. 0. 0.]
Weights  0 [-0.02  -0.11  -0.048 -0.074 -0.02 ]
Weights  0 [-0.02  -0.11  -0.048 -0.074 -0.02 ]
Weights  0 [-0.02  -0.11  -0.048 -0.074 -0.02 ]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.    -0.012  0.012 -0.046 -0.016]
Weights  0 [ 0.02   0.082  0.076 -0.02  -0.012]
Weights  0 [ 0.02   0.082  0.076 -0.02  -0.012]
Weights  0 [ 0.02   0.082  0.076 -0.02  -0.012]
Weights  0 [ 0.    -0.048  0.016 -0.124 -0.052]
Weights  0 [ 0.    -0.048  0.016 -0.124 -0.052]
Weights  0 [ 0.    -0.048  0.016 -0.124 -0.052]
Weights  0 [ 0.    -0.048 

In [ ]:
test_preds = perceptron.predict(test_data)
print(test_labels)
print(test_preds)

[ 1  1 -1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1  1 -1  1 -1  1 -1  1
  1  1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 1  1 -1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1  1 -1  1 -1  1 -1  1
  1  1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test_preds, test_labels)
print('Accuracy:', round(accuracy, 2) * 100, "%")

Accuracy: 100.0 %
